### ISSUE TITLE
🚀 [Off topic Request] Allow new users to run the project.

### ISSUE THREAD

**Issue by jaiakash** [appwrite/assistant#13]
### 🔖 Feature description

<img width="904" alt="Screenshot 2023-10-03 at 1 26 26 AM" src="https://github.com/appwrite/assistant/assets/33419526/16ddce11-c76c-4c53-9b6e-21a87c4d9f0f">

Open AI has removed the API access for any free account. I was setting up the repo to test the project.

### 🎤 Pitch

Is there any way we can help new users run this repo, especially those who don't have paid account for Open 
AI API access.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by loks0n** [comment]
Closing, unfortunately I don't think there's any way we can provide free OpenAI API key access to external users.
